#! /bin/sh

die() {
	echo $@ >&2
	exit 1
}

BUSYBOX="/bin/busybox"
test -x "$BUSYBOX" || die "could not find busybox"
"$BUSYBOX" mdev || die "mdev invocation failed"

INITCTL="/sbin/initctl"
test -x "$INITCTL" || die "could not find initctl"

case "$ACTION" in
	add)
		suffix=added
		;;
	remove|change)
		suffix="${ACTION}d"
		;;
	*)
		suffix="${ACTION}"
		;;
esac

EVENT="${SUBSYSTEM}-device-${suffix}"
ENVIRONMENT=""

OLDIFS="$IFS"
IFS='\t'
for e in $("$BUSYBOX" cat /proc/self/environ | "$BUSYBOX" tr '\0' '\t'); do
	# skip PWD, PATH
	case "$e" in
		PATH=*|PWD=*|UPSTART_JOB=*|UPSTART_INSTANCE=*)
			continue
			;;
		*)
			ENVIRONMENT="${ENVIRONMENT}'${e}' "
			;;
	esac
done
IFS="$OLDIFS"

"$INITCTL" emit -n "$EVENT" ${ENVIRONMENT} || die "initctl invocation failed"
